version: 2
jobs:
  build_android:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew
      - run:
         name: Download Dependencies
         command: ./gradlew -v
      - run:
         name: Build
         command: ./gradlew assembleDebug
      - run:
         name: Inspect
         command: |
           ls -la app
           ls -la app/build/outputs/apk
      - store_artifacts:
         name: Store APK
         path: app/build/outputs/apk
         destination: apk
workflows:
  version: 2
  build_all:
    jobs:
      - build_android
